#!/bin/bash
# Backup various files in home directory
# @author ctorchia87
#
# Example config, ~/etc/bak.stuff.conf
#   !/bin/bash
#   BACKUP_DIR_ARRAY=("/backup/$USER" "/mnt/backup")
#
#   # E.g. $HOME/Documents gets put in /backup/$USER/documents.zip/Documents
#   # and in /mnt/backup/documents.zip/Documents
#   add_to_backup_list "documents" "Documents" "$HOME"
#   add_to_backup_list "videos" "My Videos" "$HOME"
#   add_to_backup_list "music" "My Music" "$HOME"
 

function backup {
    ARCHIVE_NAME="$1"
    FILE_TO_BACKUP="$2"
    ARCHIVE_ROOT="$3"

    echo \
        name="${ARCHIVE_NAME}" \
        file="${FILE_TO_BACKUP}" \
        root="${ARCHIVE_ROOT}"

    cd "$ARCHIVE_ROOT"

    for BACKUP_DIR in ${BACKUP_DIR_ARRAY[@]}; do
        if [[ -d "$BACKUP_DIR" ]]; then
            echo backup_dir="$BACKUP_DIR"
            zip -r -u "$BACKUP_DIR/$ARCHIVE_NAME.zip" "$FILE_TO_BACKUP"
        fi
    done
}

function add_to_backup_list {
    ARCHIVE_NAME_ARRAY[${#ARCHIVE_NAME_ARRAY[@]}]="$1"
    FILE_TO_BACKUP_ARRAY[${#FILE_TO_BACKUP_ARRAY[@]}]="$2"
    ARCHIVE_ROOT_ARRAY[${#ARCHIVE_ROOT_ARRAY[@]}]="$3"
}

for CONF in ~/etc/bak.*.conf; do
    ARCHIVE_NAME_ARRAY=()
    FILE_TO_BACKUP_ARRAY=()
    ARCHIVE_ROOT_ARRAY=()

    # Conf provides backup file location and archive information used below
    echo "Sourcing $CONF"
    . "$CONF"

    for i in $(seq 0 $((${#FILE_TO_BACKUP_ARRAY[@]}-1))); do
        backup \
            "${ARCHIVE_NAME_ARRAY[$i]}" \
            "${FILE_TO_BACKUP_ARRAY[$i]}" \
            "${ARCHIVE_ROOT_ARRAY[$i]}"
    done
done
