#!/bin/bash
#
# Adds files to cumulative backup archive
# (c) 2010-2012 Carlos E. Torchia
#
# ~/etc/backup.conf must have BACKUP_DIR_ARRAY as redundant directories
# with all the backup .zip files.

. ~/etc/backup.conf

#
# This function prints the usage
#

usage()
{
  echo "usage:"
  echo "  backup <archive> <files>"
  exit 127
}

#
# Get arguments
#

if [[ -z "$1" || -z "$2" ]]; then
  usage
  exit
fi
ARCHIVE="$1"
shift

#
# Back up each file one at a time
#

while [ -n "$1" ]; do

	FILE="$1"
	shift

	for BACKUP_DIR in ${BACKUP_DIR_ARRAY[@]}; do
		# Backup to this location if possible.
		if [[ -d "$BACKUP_DIR" ]]; then
			BACKUP_ARCHIVE="$BACKUP_DIR/$ARCHIVE.zip"
			zip -r -u "$BACKUP_ARCHIVE" "$FILE"
		fi
	done
done
