#!/bin/sh
#
# Gets an FLV off of YouTube
# $1 = URL, $2.flv = filename
#

INPAGE="$1"
OUTPAGE="$2.html"
OUTFLV="$2"

echo "Getting YouTube video web page at $1"
curl -s -S -o "$OUTPAGE" "$INPAGE"

VIDEO_URL=$(/home/carlos/bin/get-yt-video-url "$OUTPAGE")

echo "Downloading the video from $VIDEO_URL as $OUTFLV"
#wget -O "$OUTFLV" "$VIDEO_URL"
#curl -L -o "$OUTFLV" "$VIDEO_URL"
curl -s -S -L -o "$OUTFLV" "$VIDEO_URL"

#
# Clean up
#

#rm "$OUTPAGE"
