#!/usr/bin/perl
#
# Gets the YouTube FLV video URL from the HTML file
# (C) 2010 Carlos E. Torchia
#

#
# Find the IDs
#

while(<>) {

  #
  # Get the video_id
  #

  if(/\&video_id\=([^\&]*)\&/) {
    $video_id="$1";
  }

  #
  # Get the "sk" ID
  #

  if(/\&sk\=([^\&]*)\&/) {
   $sk="$1";
  }

  #
  # Get the "t" ID
  #

  if(/\&t\=([^\&]*)\&/) {
    $t="$1";
  }

}

#
# Display the URL
#

$prefix='http://www.youtube.com/get_video?video_id=';

print "$prefix".$video_id.'&t='.$t."\n";
