#!/bin/sh
#
# Suspends the system
# Mostly adapted from linux.com's Manolis Tzanidakis' How To
#

##
## Get parameters, including whether to sudo first.
##

if [ "$USER" != "root" ]; then
  su -c "/home/carlos/bin/susp $@"
  exit
fi

if [ "$1" = "mem" ]; then
  STATE=mem
elif [ "$1" = "disk" ]; then
  STATE=disk
else
  echo "Invalid option '$1'" > /dev/stderr
  exit 1
fi

##
## Discover video card id
##

ID=`lspci | grep VGA | awk '{ print $1 }' | sed -e 's@0000:@@' -e 's@:@/@'`

if [ -z "$ID" ]; then
  echo "Couldn't get ID of VGA card"
  exit 1
fi


##
## Save everything
##

TMP_FILE=`mktemp /var/tmp/video_state.XXXXXX`
trap 'rm -f $TMP_FILE' 0 1 15

chvt 1

sync

cat /proc/bus/pci/$ID > $TMP_FILE


##
## Actually suspend system
##

echo -n $STATE > /sys/power/state


##
## Restore everything
##

cat $TMP_FILE > /proc/bus/pci/$ID

sleep 1
chvt 7
sleep 1
chvt 1
sleep 1
chvt 7

rm -f $TMP_FILE
